version: v1.0
name: Numberator CI
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu1804
blocks:
  - name: Workflow
    dependencies: []
    task:
      jobs:
        - name: runit
          commands:
            - checkout
            - sem-version ruby 2.5.5
            - bundle
            - rubocop
            - rake test
            - gem build numberator.gemspec
